# Plugins
gems:             ['jekyll-paginate', 'kramdown', 'rouge'] 


markdown: kramdown 

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Permalinks
permalink:        /:title/

# Setup
title:            Rede na tora 
tagline:          Natoralmente conectando 
description:      "...ou o que acontece quando uma pessoa normal se pendura na rede..."

url:            'https://redenatora.gitlab.io/' 
baseurl:        '/'

author:
  name:           'e.r.a'

paginate:         10

# Custom vars
version:          0.0.1


gitlab:
  repo:           https://gitlab.com/redenatora/redenatora.gitlab.io/
