# Plugins
gems:             ['jekyll-paginate', 'kramdown', 'rouge'] 


markdown: kramdown 

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Rede na tora 
tagline:          Natoralmente conectando 
description:      "...o que aconteceria se alguém não-técnico se aventurasse ao uso não passivo da internet?"
#url:            'https://redenatora.gitlab.io/' 
baseurl:        '/'


author:
  name:           'e.r.a'
  #  url:            https://twitter.com/karloespiritu

paginate:         7

# Custom vars
version:          1.0.1


gitlab:
  repo:           https://gitlab.com/redenatora/redenatora.gitlab.io/
