source "https://rubygems.org"

gem "jekyll", "3.3"
gem "jekyll-paginate"
gem "jekyll-gist"
gem "pygments.rb"
gem "redcarpet"
gem "jekyll-github-metadata"
gem "listen", "3.0.8"
gem "colorator", "1.1.0"
